"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ServicesProcess = exports.ServicesDetails = exports.ServicesOverview = exports.ServicesHero = void 0;
var ServicesHero_1 = require("./ServicesHero");
Object.defineProperty(exports, "ServicesHero", { enumerable: true, get: function () { return ServicesHero_1.default; } });
var ServicesOverview_1 = require("./ServicesOverview");
Object.defineProperty(exports, "ServicesOverview", { enumerable: true, get: function () { return ServicesOverview_1.default; } });
var ServicesDetails_1 = require("./ServicesDetails");
Object.defineProperty(exports, "ServicesDetails", { enumerable: true, get: function () { return ServicesDetails_1.default; } });
var ServicesProcess_1 = require("./ServicesProcess");
Object.defineProperty(exports, "ServicesProcess", { enumerable: true, get: function () { return ServicesProcess_1.default; } });
