[build]
  base = "recovery-office"
  publish = "build"
  command = "CI=false npm run build"

[build.environment]
  SKIP_TYPESCRIPT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  CI = "false"

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 