[build]
  base = "."
  publish = "build"
  command = "npm run build:netlify"

[build.environment]
  SKIP_TYPESCRIPT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"
  CI = "false"
  DISABLE_ESLINT_PLUGIN = "true"

# Redirect all routes to index.html for single-page application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 