"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Accessibility = exports.HIPAA = exports.Terms = exports.Privacy = void 0;
var Privacy_1 = require("./Privacy");
Object.defineProperty(exports, "Privacy", { enumerable: true, get: function () { return Privacy_1.default; } });
var Terms_1 = require("./Terms");
Object.defineProperty(exports, "Terms", { enumerable: true, get: function () { return Terms_1.default; } });
var HIPAA_1 = require("./HIPAA");
Object.defineProperty(exports, "HIPAA", { enumerable: true, get: function () { return HIPAA_1.default; } });
var Accessibility_1 = require("./Accessibility");
Object.defineProperty(exports, "Accessibility", { enumerable: true, get: function () { return Accessibility_1.default; } });
